ingressClassName: nginx-test
proxies:
  - name: sema
    host: sema.sadkomed.ru
    backendIP: 192.168.9.98
    backendPort: 3000
# Внутренние сервисы кластера
internal:  
  - name: argo-test
    host: argo-test.sadkomed.ru
    serviceName: argocd-server
    serviceNamespace: argocd
    backendPort: 80